include:
  - board: seeeduino_xiao_ble
    shield: totem_dongle dongle_screen
  - board: seeeduino_xiao_ble
    shield: totem_left
  - board: seeeduino_xiao_ble
    shield: settings_reset
# Right half will be added after left half is tested:
#  - board: seeeduino_xiao_ble
#    shield: totem_right
